<a href="https://colab.research.google.com/github/as123321/chatbot1/blob/master/py0806.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
vector = np.array([1,2,3,4])
matrix = np.array([[1,'Tom'],[2,'Joey'],[3,'Johnny'],[4,'Frank']])
print(vector) #一維
print(matrix) #二維

[1 2 3 4]
[['1' 'Tom']
 ['2' 'Joey']
 ['3' 'Johnny']
 ['4' 'Frank']]


In [11]:
a=np.arange(15).reshape(3,5)  #3是列 5是行2
print(a.ndim)  #判別a的維度
print(a.shape) #判別a的形狀
print(a.size) #判別a的大小

4
(2, 2, 2, 2)
16


In [6]:
from google.colab import files 
uploaded = files.upload()

#確認是否上傳成功
!ls *.* -l

Saving house-prices.csv to house-prices.csv
-rw-r--r-- 1 root root 3867 Aug  6 10:50 house-prices.csv


In [14]:
#numpy透過genfromtxt()讀取檔案
nfl =np.genfromtxt('house-prices.csv',delimiter=',')
print(nfl)


[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00 1.143e+05 1.790e+03 ... 2.000e+00       nan       nan]
 [2.000e+00 1.142e+05 2.030e+03 ... 3.000e+00       nan       nan]
 ...
 [1.260e+02 1.135e+05 2.070e+03 ... 2.000e+00       nan       nan]
 [1.270e+02 1.499e+05 2.020e+03 ... 1.000e+00       nan       nan]
 [1.280e+02 1.246e+05 2.250e+03 ... 4.000e+00       nan       nan]]


In [16]:
#加入參數後a呈現
#na表示讀取是空的,nan是數據類型轉換錯誤,genfromtxt()對於nan的類型可轉換
#dtype設定'U75'表示每個值都是75byte unicode , skip_header設置為整數
nfl =np.genfromtxt('house-prices.csv',dtype='U75',skip_header=1,delimiter=',')
print(nfl)

[['1' '114300' '1790' ... '2' 'No' 'East']
 ['2' '114200' '2030' ... '3' 'No' 'East']
 ['3' '114800' '1740' ... '1' 'No' 'East']
 ...
 ['126' '113500' '2070' ... '2' 'No' 'North']
 ['127' '149900' '2020' ... '1' 'No' 'West']
 ['128' '124600' '2250' ... '4' 'No' 'North']]


In [21]:
#多維數組的切片                                         第第  0  1  2 行
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])   # 0    5 10 15
                                                       # 1   20 25 30
                                                       # 2   35 40 45
                                                       #列
print(matrix[:,1])   #所有的列和第1行(以0開始算)
print(matrix[:,0:2])  #所有的列和第0行到第1行
print(matrix[1:3,:])   #第1列到第2列和所有的行
print(matrix[1:3,0:2])  ##第1列到第2列和第0行到第1行

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25 30]
 [35 40 45]]
[[20 25]
 [35 40]]


In [29]:
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
#加上布琳值判斷
m=(matrix==25)
print(m)
second_column_25=(matrix[:,1]==25)
print(second_column_25)
print(matrix[second_column_25,:]) #second_column_25那行全部

[[False False False]
 [False  True False]
 [False False False]]
[False  True False]
[[20 25 30]]


In [33]:
#替換空值
matrix = np.array([['5','10','15'],['20','25','30'],['35','40','']])
second_column_25=(matrix[:,:]=='')
matrix[second_column_25]='0'
print(matrix)


[['5' '10' '15']
 ['20' '25' '30']
 ['35' '40' '1']]


In [34]:
#統計方法
vector=np.array([10,20,30,40])
print(vector.sum)
matrix=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix.sum(axis=1))  #沿列相加
print(matrix.sum(axis=0))  #沿欄相加

<built-in method sum of numpy.ndarray object at 0x7fdd261c7b20>
[ 30  75 120]
[60 75 90]
